# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AltimateCode < Formula
  desc "AI-powered CLI for SQL analysis, dbt integration, and data engineering"
  homepage "https://github.com/AltimateAI/altimate-code"
  version "0.1.4"

  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AltimateAI/altimate-code/releases/download/v0.1.4/altimate-code-darwin-x64.zip"
      sha256 "af7f36b434dbfcbc641212b1bb1ce064a5108de8551452d9b5e18d3a1d973645"

      def install
        bin.install "altimate-code"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AltimateAI/altimate-code/releases/download/v0.1.4/altimate-code-darwin-arm64.zip"
      sha256 "5ed3196d810827248858a9930ee5576aafba018b7cc74a7796b6c0e03f879d74"

      def install
        bin.install "altimate-code"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/AltimateAI/altimate-code/releases/download/v0.1.4/altimate-code-linux-x64.tar.gz"
      sha256 "7fd25abab0b0535fef648a8de16b0871e4cf35b0a2ceefa93f49dd26243c0dd2"
      def install
        bin.install "altimate-code"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/AltimateAI/altimate-code/releases/download/v0.1.4/altimate-code-linux-arm64.tar.gz"
      sha256 "40b5fdb824f5d1ebb319745f8a9e94cd4528fc3dade88e292d2c721a875f649b"
      def install
        bin.install "altimate-code"
      end
    end
  end
end

